### ISSUE TITLE
Acordar la comprobación de la votación de un usuario en la misma encuesta

### ISSUE THREAD

**Issue by NachoAlesLopez** [EGC-G2-Trabajo-1718/almacenamiento#1]
Prioridad: Baja
Descripción:
Cabina de votación necesita aportar un método que comprueba si el usuario puede votar en una votación dada. De las comprobaciones realizadas, existe una comprobación de un voto doble, donde el usuario no podrá votar dos veces a la misma votación. Según se comentó en la reunión del día 29/11/2017, el módulo de almacenamiento de votos realiza la comprobación. Necesitamos por lo tanto que aporte un nuevo acceso a su API donde se podrá comprobar si el usuario ha votado en una encuesta, donde se aportará tanto el id del usuario que ha votado como el id de la votación.

**Comment by martus13** [comment]
Esa comprobación se realiza en el método "almacenar_voto" en el que nos pasáis los datos para su almacenamiento, de forma que si un usuario intenta votar varias veces a la misma pregunta se devuelve un json con el mensaje de error 400 BAD REQUEST que lo indica.
¿Os vale de esa forma?¿o necesitáis un método aparte para la comprobación?

**Comment by NachoAlesLopez** [comment]
Necesitaríamos otra forma, ya que en visualización no parece correcto permitir entrar para votar y que dé un error al terminar la votación. En vuestra API existe un método que devuelve los votos de un usuario, me gustaría tener ese método pero que filtre tanto por usuario como por votación.

**Comment by martus13** [comment]
Ya está todo. Disponéis de una llamada "comprobar_voto" al que se le pasa el usuario y la votación y devuelve 404 NOT FOUND si no se ha realizado ningún voto y 200 OK con los votos realizados por el usuario.
También disponéis de otra llamada "comprobar_voto_pregunta" al que se le pasa el usuario, la votación y la pregunta que devuelve lo mismo que el anterior, 404 si no se ha encontrado y 200 con el voto realizado.

**Comment by NachoAlesLopez** [comment]
Perfecto, ese nuevo método satisface las necesidades de comprobación de voto doble y considero el issue como solventado.
