### ISSUE TITLE
Método Almacenar Votos

### ISSUE THREAD

**Issue by jualopmun** [EGC-G2-Trabajo-1718/almacenamiento#3]
Prioridad: Media
Descripción:
En cabina de votación no tenemos muy claro el método Almacenar Votos, por lo que, me dispongo haceros  una pregunta.
   https://almacenamiento.nvotesus.es/api/post/almacenar_voto/almacenar_voto/id_usuario/id_pregunta/id_respuesta

- En el método de la API cuando se le pasa id_respuesta ¿Se le pasa la id de la pregunta o la respuesta del usuario?

Gracias.

**Comment by jesvazarg** [comment]
Buenas tardes y perdón por la tardanza,
en el método de almacenar voto se pasa como parámetros ambas id, la id de la pregunta y la id de la respuesta que ha contestado el usuario en cuestión, además también se le pasa la id del usuario y la id de la votación que ha realizado.

Hemos añadido además que en la URL se introduzca también un token para mayor seguridad a la hora de insertar los datos en nuestra BD, la cuál aún estamos implementando.

En resumen a su pregunta, en el parámetro de entrada de id_respuesta, se le pasa la id de la respuesta que ha contestado el usuario.

Espero que os haya resuelto vuestra duda.

Un saludo,
Jesús.

**Comment by NachoAlesLopez** [comment]
Buenas tardes

La respuesta que ha aportado nos produce más problemas de diseño:

1. ¿Cómo podrémos nosotros, como cabina de votación, conocer el id de la respuesta?
2. ¿Y si la respuesta consiste en un valor a introducir? Siguiendo ese sistema no se puede hacer una respuesta con ese formato. 
3. En el caso de que no se permita introducir valores, ¿en qué momento se encripta el voto? ya que si lo único en lo que consiste votar es en responder por ese método con el id de la respuesta, la votación y el token del usuario (del cual necesitamos algún método de obtención), no se podrá cifrar en ningún momento, aún menos anonimizar el usuario o que el programa no conozca su respuesta.

En nuestra opinión, el método de almacenar_voto debería consistir de un id de votación, id del usuario o algún otro método de identificación. Opcionalmente se puede dividir por preguntas, por lo que se aportará también el id de la pregunta, que sí poseemos al obtenerlo en la administración de votaciones. El contenido de la petición contendrá el voto cifrado, una cadena de números larga que contiene la respuesta del usuario a una de las preguntas de la votación, para una pregunta o para cada pregunta (en el caso de aportarse un id de pregunta).

**Comment by jesvazarg** [comment]
Buenas tardes,
no nos habíamos planteado el caso de las preguntas abiertas, así que he hablado con mi equipo para cambiar la BD y poner el texto en sí de la respuesta que haya realizado el usuario tal y como decís, tanto para preguntas abiertas como cerradas.

Perdón por la tardanza.

**Comment by NachoAlesLopez** [comment]
Buenas tardes.

Propongo que más que guardar las respuestas en sí (que permite conocer el voto del usuario), que se guarde el cifrado de la respuesta, de forma que el usuario mantenga su voto cifrado.

Una mejora aún mayor sería que se pueda enviar el voto por votación y los datos que enviemos nosotros sea el conjunto de preguntas y respuestas de la votación cifradas.

**Comment by jesvazarg** [comment]
Buenas tardes, 
Se nos olvidó poner en la wiki que los datos los recibimos encriptados, además de cifrar la respuesta, creemos que estaría bien cifrar los demás id.

Respecto a que recibamos el conjunto entero de preguntas de una votación, lo vamos a intentar realizar para la siguiente entrega. Si lo implementamos os daremos un aviso.

**Comment by jualopmun** [comment]
Hola buenas.

Nos parece correcto y esperaremos a nuevo aviso.

Gracias.

**Comment by jesvazarg** [comment]
Buenas noches,
Ya hemos implementado un nuevo método (almacenar_voto_multiple) que permite almacenar todos los votos correspondientes a un usuario y una votación dados, sin tener que realizar una llamada por cada pregunta de dicha votación.

Saludos.

**Comment by jualopmun** [comment]
Buenos días.
Agradecemos mucho por el nuevo método y por avisarnos. En principio, realizaremos cambios en nuestro código si fuese necesario.

!Muchas Gracias!
