### ISSUE TITLE
Encriptación de datos.

### ISSUE THREAD

**Issue by jucansu** [EGC-G2-Trabajo-1718/almacenamiento#4]
Prioridad: Alta

Se necesita saber que método de cifrado de datos va a realizar el equipo de Almacenamiento, para saber como se podrá desencriptar los datos necesarios para realizar el recuento de las votaciones.

**Comment by pedrosr14** [comment]
Hola, ante todo perdón por la tardanza. 

Aún estamos en pruebas viendo qué método vamos a usar porque estábamos usando implementando un método de cifrado que no permitía el descifrado después fácilmente. Ahora mismo estamos tratando de implementar el cifrado AES, cuando lo tengamos se os proporcionará el método y la clave pública que se necesita para descifrar.

**Comment by pedrosr14** [comment]
Buenas, el método para descifrar el cifrado que hemos implementado es el siguiente en python 

def decrypt(texto_encriptado, clave):
    texto_encriptado = base64.b64decode(texto_encriptado)
    iv = texto_encriptado[:AES.block_size]
    cipher = AES.new(key, AES.MODE_CBC, iv)
    return unpad(cipher.decrypt(texto_encriptado[AES.block_size:])).decode('utf-8')

**Comment by jucansu** [comment]
Buenas, ¿Nos podríais proporcionar la clave que habéis usado para encriptar? que para desencriptar se necesita la misma clave.
Además necesitaríamos saber que es lo que estáis encriptando, Si es el json al completo o parte de este, así como un ejemplo real del json encriptado y sin encriptar para probar que la desencriptación funcione correctamente.
Gracias.
