### ISSUE TITLE
Definir dependencias en un fichero requirements.txt

### ISSUE THREAD

**Issue by robgc** [EGC-G2-Trabajo-1718/almacenamiento#5]
Prioridad: Alta

Con objeto de facilitar las tareas de despliegue es importante definir todas las dependencias que vuestro subsistema necesita en un fichero requirements.txt. Aquí tenéis un enlace de referencia: https://rukbottoland.com/blog/como-instalar-paquetes-python-con-requirementstxt/

**Comment by jesvazarg** [comment]
Muchas gracias, ya está hecho.
