### ISSUE TITLE
Cambios necesarios para el despliegue automático

### ISSUE THREAD

**Issue by javsanpar** [EGC-G2-Trabajo-1718/almacenamiento#6]
- [x] El fichero principal (main) tiene que llamarse main.py .
- [x] Tiene que haber un script en la raíz del repo (junto con los otros .py) llamado prestart.sh (script en Bash), ese script debería instalar las dependencias con pip.

**Comment by robgc** [comment]
También es necesario que exista el fichero .travis.yml en la raíz de vuestro repositorio.
