### ISSUE TITLE
¿Cómo se obtiene la variable "token_bd"?

### ISSUE THREAD

**Issue by yamikadesu** [EGC-G2-Trabajo-1718/almacenamiento#7]
Prioridad: Alto
Descripción: Aunque la definición queda clara "- token_bd: (String) Token para autenticarse y acceder a nuestra BBDD", no hay detallada un forma de obtenerlo o saber qué valores se tienen asignados para esa variable.

**Comment by jesvazarg** [comment]
Perdón por no facilitarla antes, pero no sabía si iba a tener más cambios y se me pasó luego.
Introduce esto en el token_db -> QWERTY12345
Es uno de los que hay guardados.
Si por algún casual se llegase a cambiar os avisaríamos (como muy tarde se cambiaría el código el viernes aunque no creo)

Si tenéis alguna duda comunicárnoslo.
