### ISSUE TITLE
¿Valor correcto del token_bd?

### ISSUE THREAD

**Issue by yamikadesu** [EGC-G2-Trabajo-1718/almacenamiento#9]
Prioridad: Alto
Descripción: He visto en la incidencia #7 (la mía) y la incidencia #8 y me preguntaba si realmente el token_bd que se me proporcionó es el correcto porque resulta extraño que tengan esos valores.

**Comment by jesvazarg** [comment]
Tenemos varios tokens guardados para repartirlo a diferentes personas, así que no hay problemas con vuestra clave.
